#!/usr/bin/env perl

use strict;
use FindBin qw($Bin $Script);

use lib "$Bin";
use glm_preprocessor;
use glm_database;
use glm_manifest;

my %opts = ();

use Getopt::Long;
Getopt::Long::Configure("bundling");
unless (GetOptions(
    \%opts,
    "help|h" => sub {print_usage();},
)) {
    print_usage();
};

#print_usage() && exit() if (scalar(@ARGV) != 2);
#print_usage() && exit() if (scalar(@ARGV) != 1);

my $preprocessor = glm_preprocessor->new(filenames => \@ARGV);
my $db = glm_database->new(input_handle => $preprocessor->input_handle);
my $manifest = glm_manifest->new(db => $db);

exit(0);

sub print_usage {
    print <<EOF
Usage: $Script <database> <list>
EOF
}


__DATA__

=head1 NAME

$Script - manage gear lists

=head1 SYNOPSIS

B<$Script> --help|-h

B<$Script> <database> <format>

=head1 OPTIONS

=over

=item B<--help|-h>

This message.

=back

=head1 DESCRIPTION

$Script takes a gear database and a gear manifest to create a gear list.

=cut
