#!/usr/bin/env perl

use strict;
use FindBin qw($Script);

use glm_database;
use glm_manifest;

my %opts = ();

use Getopt::Long;
Getopt::Long::Configure("bundling");
unless (GetOptions(
    \%opts,
    "help|h" => sub {print_usage();},
)) {
    print_usage();
};

print_usage() && exit() if (scalar(@ARGV) != 2);

my $db = glm_database->new(filename => shift);
my $manifest = glm_manifest->new(filename => shift, db => $db);

exit(0);

sub print_usage {
    print <<EOF
Usage: $Script <database> <list>
EOF
}


__DATA__

=head1 NAME

$Script - manage gear lists

=head1 SYNOPSIS

B<$Script> --help|-h

B<$Script> <database> <format>

=head1 OPTIONS

=over

=item B<--help|-h>

This message.

=back

=head1 DESCRIPTION

$Script takes a gear database and a gear manifest to create a gear list.

=cut
